### ISSUE TITLE
Explore Sphinx - OSDMP

### ISSUE THREAD

**Issue by jfmartinez4** [ciesin-geospatial/TOPSTSCHOOL-OSDMP#20]
Generate a sample of the water lesson 1 using sphynx: https://ciesin-geospatial.github.io/TOPSTSCHOOL-water/m101-wsim-gldas.html
https://github.com/ciesin-geospatial/TOPSTSCHOOL-water/blob/main/m101-wsim-gldas-python.qmd
If sample can be done, determine SWOT (pros and cons) on time and ease for transition.

**Comment by xames3** [comment]
- @jfmartinez4, I was/am running into issues with getting R/Studio running on my system. I'll be reinstalling the whole thing once the new macOS 15 releases tomorrow. Till then, I've started working on the Python code.
- I'll share my updates here in this thread.

**Comment by xames3** [comment]
- upgraded my system to the latest macOS Sequoia 15.0 build. I believe I should be able to install R/Studio on it. Will check and rewrite the code.

**Comment by jfmartinez4** [comment]
@xames3 thanks for the update. Let me know if I can help with anything

**Comment by xames3** [comment]
no worries, @jfmartinez4. by the way, for [this](https://github.com/orgs/ciesin-geospatial/projects/2?pane=issue&itemId=79762058) draft, I've found a solution to work with collapsible views for `xarray`'s outputs. you can assign the ticket to either me and/or someone else who is working on `quarto` rendering. I've added that snippet of code to my `sphinx` build with all the explanations. will share the results soon.

**Comment by xames3** [comment]
@kyttmacmanus, as part of the initial deliverables by next Wednesday, (September 25, 2024), I'd be sharing the work done as part of this issue. this involves:
- complete deployment workflow from local feature branch to main website deployment.
- complete migration of water module (lesson 1) with updated code snippets and other deliverables like Jupyter notebooks, data sources, stock image placeholders, etc.
- planning to do just the python build as of now as I've still not installed R/Studio yet because of some system issue else will test it out on my development virtual machine.

Once this is demoed, could you or anyone from the TOPST team could review the content and make sure it looks okay or if anything needs to be changed/added to it?

**Comment by xames3** [comment]
@jfmartinez4, could I ask questions to the CIESIN/SCHOOL development team during the demo? I've almost migrated the complete code to match the existing site but I found a couple of discrepancies which I wasn't able to resolve nor understand.

**Comment by jfmartinez4** [comment]
@xames3 Yeah of course, but please keep in mind that these Open Science tools are relatively new and we might not have all the answers. Part of this exercise is to learn from you as well.

**Comment by xames3** [comment]
got it, @jfmartinez4! thanks for that morale boost! 😎

**Comment by jfmartinez4** [comment]
- Added changes and updates including glossary
- Met with NASA team
- NOTES:
Notes by JFM
Introductions
Sphinx website: https://www.sphinx-doc.org/en/master/
SCHOOL OSDMP github: https://github.com/ciesin-geospatial/TOPSTSCHOOL-OSDMP
SPhinx is like quarto, it's a language using restructured text as the markdown language
Several capabiliies to simplify text and web page building. 
folium is an open source package to display maps on leaflet layouts
Sphinx is more customizable but there's a steep learning curve.
Quarto uses markdown and Sphynx cannot read markdown. 
Issues with sustainability and maintenance due to half way through the project.
Lack of time to maintain that would remove time with more content. 
There is a need for landing website. 
Leaving the vignettes alone. 
Using Sphynx as landing page and redirecting to landing pages of quarto is a possibility. 
Hybrid solution with feature rich content for front page and link out to quarto or embed quarto within sphynx. 
SPhynx is a stable platform and will be around for a while. Not modern and relies on old python code. 
Dash plotly widgets .
Possible swapping out the static results for more dynamic widgets.
