### ISSUE TITLE
Revise and refactor the content of the index page

### ISSUE THREAD

**Issue by xames3** [ciesin-geospatial/TOPSTSCHOOL-OSDMP#25]
- after discussion with @Alinka8, she would be working on rewording and refactoring the initial bits of the work done so far. this is to make sure the contributor gets a feel of the whole system and blends in for the upcoming contributions.
- expected output is basically an overhaul of the current index/landing page to make sure we put more information with relevant details (photos, videos, links, etc.) to make the experience of future contributors easier to navigate and thus encouraging them for further collaboration.

**Comment by xames3** [comment]
- initial deliverables would be a simple note or a document with the updated content with ideas for images, videos, links, blog post, etc. with placements/placeholders which we will populate later after review by someone from the TOPST Development Team.

**Comment by Alinka8** [comment]
Hello Akshay! I have started working on it.

**Comment by xames3** [comment]
- added changes to remote, closing...
