### ISSUE TITLE
Module #2 Dockerfile

### ISSUE THREAD

**Issue by joshbrinks** [ciesin-geospatial/TOPSTSCHOOL-OSDMP#42]
[Module 2 dockerfile](https://github.com/ciesin-geospatial/TOPSTSCHOOL-air-quality/blob/16464ca583511bb59587734e5f2ee184590b026f/dockerfile) needs to be updated for all python packages required for all modules and then tested as working with each lesson. 

Notify me when complete so I can verify and update our registry.

**Comment by xames3** [comment]
I believe this issue should be opened under air quality, right? @joshbrinks and @jfmartinez4

**Comment by jfmartinez4** [comment]
@joshbrinks @xames3 this issue has been moved to the appropiate Repo (Air quality)

**Comment by joshbrinks** [comment]
What is this repo for. It has no readme or other documentation.

**Comment by jfmartinez4** [comment]
@joshbrinks Akshay was testing Sphynx capabilities that he presented to the team a few weeks ago.

**Comment by joshbrinks** [comment]
OK a readme would be a good idea.
