### ISSUE TITLE
Need to draw a project flow diagram

### ISSUE THREAD

**Issue by xames3** [ciesin-geospatial/TOPSTSCHOOL-OSDMP#9]
- as what the title says, need to come up with a high-overview project flow diagram to show the end-to-end flow of the project and the underlying processes.

**Comment by xames3** [comment]
- @gv2325 and @jfmartinez4, check out [git-flow](https://raw.githubusercontent.com/ciesin-geospatial/TOPSTSCHOOL-OSDMP/dev/assets/TOPST%20SCHOOL%20GitFlow.png) for the repository. This is the same process that we discussed in today's meeting.
- need to work on end-to-end workflow diagram next. Please feel free to share your suggestions on this one. I'll commit the raw draw.io file as well a little later.

**Comment by gv2325** [comment]
I like draw.io, we've been using it in our other projects.

**Comment by xames3** [comment]
- updated [git-flow](https://raw.githubusercontent.com/ciesin-geospatial/TOPSTSCHOOL-OSDMP/dev/assets/tops-school-git-flow.png) and [roadmap](https://raw.githubusercontent.com/ciesin-geospatial/TOPSTSCHOOL-OSDMP/dev/assets/topst-school-story-map.png) with draw.io source files.
- need to work on a high-level process flow diagram next.
